apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
spec:
  args:
  - name: service-name
  metrics:
  - name: {{ template "helm-guestbook.fullname" . }}
    successCondition: result[0] >= 0.00001
    provider:
      prometheus:
        address: "http://a0179abbebc504fe1a02cc2868d10d20-1436141555.us-east-2.elb.amazonaws.com:9090"
        query: |
          rate(nginx_ingress_controller_requests{ingress="guestbook-helm-guestbook", controller_class="nginx",exported_namespace="guestbook-helm-guestbook",status=~"[2].*"}[24h])