apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    successCondition: result[0] == NaN || result[0] >= 0.10
    provider:
      prometheus:
        address: "http://a0179abbebc504fe1a02cc2868d10d20-1436141555.us-east-2.elb.amazonaws.com:9090"
        query: |
          rate(nginx_ingress_controller_requests{ingress="{{ {{ template "helm-guestbook.fullname" . }} }}", controller_class="nginx",exported_namespace="{{ {{ template "helm-guestbook.fullname" . }} }}",status!~"[4-5].*"}[1h]) / rate(nginx_ingress_controller_requests{ingress="{{ {{ template "helm-guestbook.fullname" . }} }}", controller_class="nginx",exported_namespace="{{ {{ template "helm-guestbook.fullname" . }} }}"}[1h])