apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    successCondition: result[0] <= 0.10
    provider:
      prometheus:
        address: "http://a0179abbebc504fe1a02cc2868d10d20-1436141555.us-east-2.elb.amazonaws.com:9090"
        query: |
          round(sum(irate(nginx_ingress_controller_requests{controller_pod=~"$controller",controller_class=~"nginx",controller_namespace=~"ingress-nginx",ingress=~"$ingress"}[2m])) by (ingress), 0.001)